name: CI

on:
  push:
    branches:
      - v2-main
  pull_request:
    branches:
      - v2-main
  workflow_dispatch:

permissions: read-all

jobs:
  build:
    name: Build on ROS 2 ${{ matrix.ros_distro }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    container:
      image: ros:${{ matrix.ros_distro }}-ros-core
    env:
      ROS_DISTRO: ${{ matrix.ros_distro }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - ros_distro: humble
            os: ubuntu-22.04
          - ros_distro: jazzy
            os: ubuntu-24.04

    steps:
      - name: Install build tools
        run: |
          apt-get update
          apt-get install -y \
            build-essential \
            cmake \
            file \
            git \
            python3-colcon-common-extensions \
            python3-rosdep \
            sudo
          rosdep init || true
          rosdep update --rosdistro ${ROS_DISTRO}

      - name: Setup ROS 2 workspace
        run: mkdir -p ${GITHUB_WORKSPACE}/ros2/src

      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          path: ros2/src/OrbbecSDK_ROS2

      - name: Install declared dependencies
        shell: bash
        run: |
          source /opt/ros/${ROS_DISTRO}/setup.bash
          cd ${GITHUB_WORKSPACE}/ros2
          rosdep install -i --reinstall --from-path src --rosdistro ${ROS_DISTRO} -y

      - name: Build OrbbecSDK ROS 2 wrapper from source
        shell: bash
        run: |
          set -e
          source /opt/ros/${ROS_DISTRO}/setup.bash
          cd ${GITHUB_WORKSPACE}/ros2
          PYTHONPATH=/opt/ros/${ROS_DISTRO}/lib/python3/dist-packages:${PYTHONPATH} \
            colcon build --symlink-install --merge-install --event-handlers console_direct+
